#
# Copyright 2010-2012 Free Software Foundation, Inc.
#
# This file was generated by gr_modtool, a tool from the GNU Radio framework
# This file is a part of gnuradio
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
#
'''
This is the GNU Radio GNMAX2769 module. Place your Python package
description here (python/__init__.py).
'''
from __future__ import unicode_literals

# import swig generated symbols into the gnMAX2769 namespace
try:
    # this might fail if the module is python-only
    from .gnMAX2769_swig import *
except ImportError:
    pass

# import any pure python here
#
